version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}


services:


  ### PHP-FPM,NGINX,supervisor Server #########################################
  nginx:
    build:
      context: ./nginxphp
    volumes:
      - /kalading/webroot:/kalading/webroot
      - /kalading/webroot/nginx:/etc/nginx/conf.d/
      - /kalading/webroot/supervisor:/etc/supervisor/conf.d
    ports:
      - "80:80"
      #- "443:443"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
      #replace_extra_host#

    networks:
      - backend

